name: Deploy Mkdocs
on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grant write permissions to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install mkdocs-material "mkdocs-material[imaging]" mkdocs-material[extensions]
      - run: mkdocs gh-deploy --force
